---
title: "Brown Shrimp EDM Testing"
author: "Lew Coggins"
date: "5/23/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(kableExtra)
library(tidyr)
library(dplyr)
library(GPEDM)
library(ggplot2)
library(tidyr)
library(rEDM)

```

## Brown Shrimp

```{r BrownShrimpEdm,echo=FALSE,warning=FALSE}

rm(list = ls())

setwd("C:\\Users\\lewis.coggins\\Documents\\GitHub\\EDMShrimp")


#Read Data from Chen-han

dat<-read_xlsx("SEAMAPBrownSummer.xlsx")
dat=cbind(dat,rowMeans(dat[,-1]))
colnames(dat)[11]<-"mean"
#dat[,-1]=scale(dat[,-1],center=T)
zones=c("zone_11","zone_14","zone_15","zone_16","zone_17","zone_18","zone_19","zone_20","zone_21","mean")
e=c(3,3,4,4,6,5,7,2,3)#e=rep(7,9)

for(i in 1:9){

inpdat=as.data.frame(cbind(dat$Time,dat[[zones[i]]]))
inpdat=as.data.frame(cbind(inpdat[,1],rep(zones[i],dim(inpdat)[1]),inpdat[,2]))
inpdat[,3]=as.numeric(inpdat[,3]);inpdat[,1]=as.numeric(inpdat[,1])
names(inpdat)<-c("Time","Zone","Index");inpdat
N=nrow(inpdat)

cat("  \n")
ShrimpZone=fitGP(data = inpdat, y = "Index", pop = "Zone", E=e[i], tau=1, scaling = "local", predictmethod = "loo")
summary(ShrimpZone)

#> Plotting out of sample results.
#plot(ShrimpZone)

plot(inpdat$Time,ShrimpZone$inputs$y,col='black',type='p',ylab='Index',xlab='Year',main=zones[i])
lines(inpdat$Time,ShrimpZone$insampresults$predmean,col='red',lty=2)
lines(inpdat$Time,ShrimpZone$outsampresults$predmean,col='blue')
#legend('topright',legend=c("Observed","InSampPred","OutSampPred"),pch=c("o","",""),lty=c(0,1,2),col=c('black','red','blue'),bty='n')
legend('topright',legend=c("OutSampPred","InSampPred"),lty=c(1,2),col=c('blue','red'),bty='n')
rho=ComputeError(ShrimpZone$outsampresults$obs, ShrimpZone$outsampresults$predmean)$rho
text(1995,max(ShrimpZone$outsampresults$obs,na.rm=T),paste('rho=',round(rho,2)))
text(1995,max(ShrimpZone$outsampresults$obs,na.rm=T)*.95,paste('E=',e[i]))

}

```